let str = 'Hello'.slice(1 , 5)
console.log(str.length)
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.replace('Hello' , 'Aadil'))
console.log(str.replaceAll('l' , 'a'))
// console.log(str.slice(0 , 1))